# Generated by Django 2.0.5 on 2018-07-03 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='moibile',
            new_name='mobile',
        ),
    ]
