# Generated by Django 2.0.5 on 2018-07-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpauser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='mpauser',
            name='phone_number1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
